### ISSUE TITLE
Detect header says it takes vectors, but the cpp function takes floats

### ISSUE THREAD

**Issue by rlewkowicz** [spacewalk01/tensorrt-openpose#10]
Title. It causes issues at link time. I see folks have made this work, 

https://github.com/spacewalk01/tensorrt-openpose/blob/main/trt_demo/Openpose.h#L37
https://github.com/spacewalk01/tensorrt-openpose/blob/main/trt_demo/Openpose.cpp#L3

Looks like folks have built this, but idk how

**Comment by spacewalk01** [comment]
@rlewkowicz thank you for pointing this out

**Comment by spacewalk01** [comment]
fixed it. Will you try it again?
