### ISSUE TITLE
About attitude tracking real-time accuracy

### ISSUE THREAD

**Issue by zhanghongyong123456** [spacewalk01/tensorrt-openpose#3]
I was testing the performance and I couldn't keep up with the pose，I can't keep up with the action，I need to adjust those parameters or Ihave a better model, what do I do,I was hoping you could give me some advice，Thank you ever so much
![26](https://user-images.githubusercontent.com/48466610/126760301-9f4eb3bd-5a34-449d-959d-ebc6c2d309f5.png)

**Comment by batselem** [comment]
The current trt_pose is trained with `224x224` input size which is quiet small `(resnet18_baseline_att_224x224_A)`. For better performance, you may consider training a larger model.

**Comment by zhanghongyong123456** [comment]
> The current trt_pose is trained with `224x224` input size which is quiet small `(resnet18_baseline_att_224x224_A)`. For better performance, you may consider training a larger model.

That is to say, there is no other way to improve accuracy than by training the model，Have you tested the performance of densenet121 model，Can we implement Openpose（https://github.com/CMU-Perceptual-Computing-Lab/openpose） to implement tensorRT，

**Comment by zhanghongyong123456** [comment]
> The current trt_pose is trained with `224x224` input size which is quiet small `(resnet18_baseline_att_224x224_A)`. For better performance, you may consider training a larger model.

I found a Tensorrt Openpose based on Caffemodel. How about this，https://github.com/zerollzeng/tensorrt-zoo/issues?q=window  ，Do you think it would help you， I want to configure it under Windows, but I am not familiar with the cmake compilation process. Could you please give me a Cmake GUI configuration process? Thank you

**Comment by spacewalk01** [comment]
I didn't test it but I assume it will be slightly better than resnet. You may try it and let me know the result.

**Comment by spacewalk01** [comment]
https://github.com/NVIDIA-AI-IOT/trt_pose/issues/59#issuecomment-668252922

**Comment by spacewalk01** [comment]
Check this out. https://github.com/tensorlayer/hyperpose

**Comment by zhanghongyong123456** [comment]
> I didn't test it but I assume it will be slightly better than resnet. You may try it and let me know the result.

I am now in Win10 compilation failed，This guy compiled it, but I didn't，https://github.com/drostifrosti/tensorrt-zoo  Can you try it on

**Comment by spacewalk01** [comment]
Just found out about the following blog to train larger models. [link](https://docs.nvidia.com/isaac/isaac/packages/skeleton_pose_estimation/doc/2Dskeleton_pose_estimation.html)

**Comment by zhanghongyong123456** [comment]
> Just found out about the following blog to train larger models. [link](https://docs.nvidia.com/isaac/isaac/packages/skeleton_pose_estimation/doc/2Dskeleton_pose_estimation.html)

Thank you very much for your response，I have a look at
