### ISSUE TITLE
what is the code in this line mean?  

### ISSUE THREAD

**Issue by DongLizhong** [spacewalk01/TensorRT-Openpose#4]
https://github.com/spacewalk01/TensorRT-Openpose/blob/248de017b7841b033605a17c3f67c606dceaf402/trt_demo/resize.cu#L44

**Comment by spacewalk01** [comment]
it is a kernel function for resizing input images on cuda. I used it from https://github.com/CaoWGG/TensorRT-YOLOv4 source code.
