### ISSUE TITLE
How to use another engine in this programme

### ISSUE THREAD

**Issue by HeZhaoyang111** [spacewalk01/tensorrt-openpose#5]
Hello, I have just run the demo, and it ran smoothly. Now I want to change the engine and to build a new one from the offical model from https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/models/pose/body_25  . I have just transformed the caffe model to engine, but it does not  work on this program.  The error is : Cuda Error in cuInt8::NCHWToNHWC: 1 (invalid argument) FAILED_EXECUTION: Unknown exception

I wonder is this program only fitted to the resnet model? If so, how can I adapted it to my own?

**Comment by spacewalk01** [comment]
You can load and run CMU openpose models with onnx format using TensorrtPoseNet.cpp without changing the code (I didn't test it with caffe model) but for body_25 model version or any other network, you need to modify Openpose.cpp according to the network output. Openpose.cpp parses the resnet output and computes the connectivity between the joints which is shown below.

![image](https://user-images.githubusercontent.com/6389915/135034639-f40a2a80-4886-4e95-885e-6fa00840a66b.png)

**Comment by spacewalk01** [comment]
You may consider https://github.com/htshinichi/caffe-onnx for converting caffe to onnx to prevent the above error.

**Comment by spacewalk01** [comment]
please show me full error message and line at which the error occurs.
NCHWToNHWC

**Comment by HeZhaoyang111** [comment]
Thanks for reply! Yet I used the code from https://github.com/htshinichi/caffe-onnx to get the onnx file, and then transfom it to engine file. But it does not work. I consider maybe the N C H W prameter is not right.  That's the full error message, and it occurs when the vedio is processed, So I cannot figure our where it occurs.
![15d0ea4749f7d6e07a8c6089bdb770a](https://user-images.githubusercontent.com/59993686/135036330-ffa3059e-2536-421f-a008-933626fed061.jpg)
..

**Comment by spacewalk01** [comment]
I see. Please let me know the following output. 
```
	std::cout << "Model input shape: " <<
		batchSize << "x" << 
		numChannels << "x" << 
		inputWidthSize << "x" << 
		inputHeightSize << std::endl;
```

**Comment by HeZhaoyang111** [comment]
Where shell I add this code? Sorry, I am not so familar with the code, does the batchSize, numChannels, inputWidthSize, inputHeightSize means N,C,H,W in this programme?

**Comment by HeZhaoyang111** [comment]
The first one is the res model ,and it can run smoothly, while the second one is my model
![f2c228f01aadee7070393b476084383](https://user-images.githubusercontent.com/59993686/135038942-a8308113-7fd0-4ab3-b430-478639882412.jpg)
.
![5e871e766011e28d77c22773b5da1d4](https://user-images.githubusercontent.com/59993686/135038963-07fd7d79-ae53-43d3-bd5e-e8d85c6cee28.jpg)

**Comment by spacewalk01** [comment]
Model input (image) shape is 3x16x16 and it is too small. and the output is also 2x2. I think it is not correctly converted to onnx. Or you may check the output shape of your caffe model before converting it to Tensorrt engine. Check out this one https://github.com/vadimkantorov/caffemodel2pytorch 

Also, this model input shape and output shape is not dependent on the video. It is fixed. When the video frame comes, the frame  is resized to model input shape which is 224x224 in resnet case.

**Comment by HeZhaoyang111** [comment]
Thanks! I will check out and convert to the engine again.

**Comment by HeZhaoyang111** [comment]
I noticed that the model's parameter I used is initialized by 3,16,16, thus I changed it mannually by 3 224 224, this time there are points shown in the vedio but there is still something wrong. I guess this may be due to the figure's topology
![4QNX@2PW4HCUOMC~SLG(DA](https://user-images.githubusercontent.com/59993686/135049263-004c55d9-d41c-439e-badf-bd67ef2271cd.png)
![72bc608d476c035dde0051dafa2231b](https://user-images.githubusercontent.com/59993686/135050023-1550076b-2d63-4c94-82e5-f2726c439763.jpg)

y

**Comment by HeZhaoyang111** [comment]
Thanks! And I want to know why the model is only trained for 249 epoches? In the offical repo of CMU, I notice they trained their model for more than 440000 epoches. And do you know how to change this hyperprarmeter? I guess more training may perform better.

**Comment by chh7411898** [comment]
Hi !  Did you succeed in this project?  use bpby_25 model

**Comment by chh7411898** [comment]
Hi ! Did you succeed in this project? use body_25 model
