### ISSUE TITLE
Tensorrt context inference error

### ISSUE THREAD

**Issue by guotonglucky** [spacewalk01/TensorRT-Openpose#6]
Hello, when I ran the demo, I found that the context would report an error when inference.
Native environment:
Windows 10
Visual Studio 2019
RTX 2080 Ti GPU
TensorRT 7.2.3.4
CUDA 11.1, Cudnn 8
Python 3.6
Torch 1.8.1
OpenCV 4.5.1 with CUDA
![image](https://user-images.githubusercontent.com/50897229/136644996-8e48911e-e553-4b40-8cc9-2601f3bd944a.png)
![image](https://user-images.githubusercontent.com/50897229/136645039-e634a85e-8b32-4bae-95dd-3059304685c7.png)

**Comment by spacewalk01** [comment]
@guotonglucky check out this one: https://github.com/pytorch/pytorch/issues/31285

It says that for Geforce RTX 2080 Ti, Compute Capability is 7.5. 
i think you need to install the version of cuda that is compatible with your GPU.

**Comment by guotonglucky** [comment]
I tried cuda10.2 and TensorRT-7.2.1.6.Windows10.x86_64.cuda-10.2.cudnn8.0 and it works.
thank you very much.
I use trtexec.exe and will report an error: The engine plan file is not compatible with this version of TensorRT. So I use C++ Tensorrt to generate engine files.
