### ISSUE TITLE
change another model

### ISSUE THREAD

**Issue by chh7411898** [spacewalk01/TensorRT-Openpose#7]
你好,当我使用从IMU官方的模型 从caffe转换到engine  然后使用这个代码 发现输出的结果不太理解，而且维度也有点区别
下图是输出信息
![微信图片_20211221093230](https://user-images.githubusercontent.com/39481475/146855568-93a8c4ae-476a-4ead-b54d-9f2839b0903d.png)

**Comment by spacewalk01** [comment]
Will you try to resize model with 244x244 shape and convert it to tensorrt engine?
https://github.com/spacewalk01/TensorRT-Openpose/issues/5#issuecomment-928912605

**Comment by chh7411898** [comment]
yes i have adready resize  224x224 by modify by CMU  input: "image"
input_dim: 1
input_dim: 3
input_dim: 224 # This value will be defined at runtime
input_dim: 224 # This value will be defined at runtime

**Comment by chh7411898** [comment]
but the result very poor  this is my input and output 
![U
