### ISSUE TITLE
but the result very poor  this is my input and output

### ISSUE THREAD

**Issue by chh7411898** [spacewalk01/tensorrt-openpose#8]
but the result very poor  this is my input and output 
this is input and out
![1](https://user-images.githubusercontent.com/39481475/146863634-31211042-b959-48c4-840c-80b1b0fd462f.png)
![2](https://user-images.githubusercontent.com/39481475/146863664-e64eec24-fcde-4880-aaf1-bdbb5fcc0927.png)

_Originally posted by @chh7411898 in https://github.com/spacewalk01/TensorRT-Openpose/issues/7#issuecomment-998429012_

**Comment by chh7411898** [comment]
i think  1x19x28x28  store keypoint heatmap   and 1x38x28x28 store paf relation so what should i modify your code ?  i have see the before issue, you suggest modify openpose.cpp

**Comment by spacewalk01** [comment]
for 244x244 model, the input and output of the imported engine should be as follows:
![image](https://user-images.githubusercontent.com/6389915/146867788-3dc8f64a-e2da-4c14-b834-b7fc4462326b.png)

**Comment by spacewalk01** [comment]
You may try to modify the openpose.cpp according to your model output.

**Comment by chh7411898** [comment]
![3](https://user-images.githubusercontent.com/39481475/146868464-394e02f7-34c2-4b91-baa4-424861431153.png)
this is my 224x224 model  output info
![Uploading 3.png…]()

**Comment by chh7411898** [comment]
i think ouuput[0] and output[1] should swap the location

**Comment by chh7411898** [comment]
hi  how to define topology   in  the openpose.h   i  want modift to CMU office fomat
