### ISSUE TITLE
I am getting a crash running this

### ISSUE THREAD

**Issue by danishansari** [spacewalk01/TensorRT-Openpose#9]
@spacewalk01 thanks for this great implementation.
I am having some trouble using this repo.

This line in the code does not make sense to me:    [https://github.com/spacewalk01/TensorRT-Openpose/blob/14714f954875f054f3aab827700f7f1d9f677500/trt_demo/parse/paf_score_graph.cpp#L94](https://github.com/spacewalk01/TensorRT-Openpose/blob/14714f954875f054f3aab827700f7f1d9f677500/trt_demo/parse/paf_score_graph.cpp#L94)
Here counts is a vector of size N*C, C and N are coming from dimensions of input (NCHW) which is 1x3x224x224.
So counts is having a size 3, in the same functions, it's trying to access indexes larger than 2, which is coming from topology,
and that's reason for crash I am getting in [https://github.com/spacewalk01/TensorRT-Openpose/blob/14714f954875f054f3aab827700f7f1d9f677500/trt_demo/parse/paf_score_graph.cpp#L24](https://github.com/spacewalk01/TensorRT-Openpose/blob/14714f954875f054f3aab827700f7f1d9f677500/trt_demo/parse/paf_score_graph.cpp#L24)

here **b** is having garbage as it's coming from counts[4], while counts is having on 3 values.

This is how I am using it:

```
#include "trt_demo/Openpose.h"
#include "trt_demo/TensorrtPoseNet.h"

#include <string>

int main() {

    TensorrtPoseNet *trt_pose = new TensorrtPoseNet("trt_pose_fp16.engine", 0.9, 0.1);
    std::string filepath="images/image.png";

    cv::Mat img = cv::imread(filepath);

    if (img.rows > 0 and img.cols > 0) {
        cv::resize(img, img, cv::Size(224, 224));
        std::cout << "input image shape:" << img.rows << "x" << img.cols << std::endl;
        trt_pose->infer(img);

        for (int i = 0; i < trt_pose->inputDims.size(); i++) {
            std::cout << "dims: " << trt_pose->inputDims[i].d[0] << " " << trt_pose->inputDims[i].d[1] <<
                    " " << trt_pose->inputDims[i].d[2] << " " << trt_pose->inputDims[i].d[3] << std::endl;
            Openpose *openpose = new Openpose(trt_pose->inputDims[i]);
            openpose->detect(trt_pose->cpuCmapBuffer, trt_pose->cpuPafBuffer, img);
        }
    }
    return 0;
}
```

I am doing something wrong here? Could please you share a sample-code explaining how to use this?

**Comment by spacewalk01** [comment]
Thank you for the bug report. I will look into it and get back to you.

**Comment by spacewalk01** [comment]
I haven't tested it but it should work. Let me know
```
#include "TensorrtPoseNet.h"
#include <opencv2/core.hpp>
#include <iostream>
#include <fstream>
#include <chrono>
#include <string> 
#include <map>
#include "opencv2/imgcodecs.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/imgproc.hpp"
#include "Openpose.h"

using namespace cv;
using namespace std::chrono;

int main() {

      std::string filepath="images/image.png";
   
    // Initialize TensorRT
	float confThreshold = 0.3f;
	float nmsThreshold = 0.3f;
	TensorrtPoseNet net("trt_pose_fp16.engine", 0.9, 0.1);
	
	// Initialize OpenPose Parser
	Openpose openpose(net.outputDims[0]);
	int* object_counts;
	int* objects;
        float* refined_peaks; 

    cv::Mat img = cv::imread(filepath);

    if (img.rows > 0 and img.cols > 0) {
        // You don't need to resize. Image will be resized in TensorRT Module.
      net.infer(img);  // resnet infers candidate points and stores temp data in cmap buffer and paf buffer
      openpose.detect(net.cpuCmapBuffer, net.cpuPafBuffer, img); // openpose algorithm finds connection between points in multiple people from the buffers
      imshow("Result", frame);
      waitKey(0);

    }
    return 0;
}
```
